# Generated by Django 6.0.3 on 2026-03-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the doctor', max_length=100)),
                ('specialty', models.CharField(choices=[('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('pediatrics', 'Pediatrics'), ('psychiatry', 'Psychiatry'), ('radiology', 'Radiology'), ('surgery', 'Surgery')], help_text='Medical specialty', max_length=50)),
                ('email', models.EmailField(help_text='Contact email', max_length=254, unique=True)),
                ('phone', models.CharField(help_text='Phone number', max_length=15)),
                ('address', models.TextField(blank=True, help_text='Clinic address')),
                ('years_experience', models.PositiveIntegerField(default=0, help_text='Years of experience')),
                ('is_available', models.BooleanField(default=True, help_text='Currently accepting patients')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['name'],
            },
        ),
    ]
